[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/vless"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["deno"]
